[package]
name = "sltf_vm"
version = "0.1.0"
authors = ["Steven Troxler <steven.troxler@gmail.com>"]

[dependencies]
sltf_parse = {path = "../sltf_parse"}
either = "1.5.0"

[dev-dependencies]
pretty_assertions = "0.5.1"
