[package]
name = "sltf_parse"
version = "0.1.0"
authors = ["Steven Troxler <steven.troxler@gmail.com>"]

[dependencies]
regex = "1"
lazy_static = "1.1.0"

[dev-dependencies]
pretty_assertions = "0.5.1"
